name: MyUnicircle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  flutter_icons: ^1.1.0
  bubble: ^1.1.9+1
  google_fonts: ^1.0.0
  flutter_svg: ^0.19.0
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4
  pin_entry_text_field: ^0.1.3
  camera: ^0.5.8+2
  simple_animations: ^1.3.12
  charts_flutter: ^0.9.0
  local_auth: ^0.6.2+3
  cloud_firestore: ^0.14.0+2
  permission_handler: ^3.0.0
  firebase_auth: ^0.18.0+1
  mvc_pattern: ^3.4.1
  # modal_bottom_sheet: ^0.2.0+1
  photo_view: ^0.9.2
  global_configuration: ^1.3.0
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  firebase_storage: ^4.0.0
  timeago: ^2.0.26
  dio: ^3.0.9
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.7+7
  emoji_picker: ^0.1.0
  multi_image_picker: ^4.7.12
  path_provider: ^1.6.11
  flutter_paystack: ^1.0.3+1
  shimmer: ^1.0.0
  agora_rtc_engine: 1.0.5
  flutter_datetime_picker: ^1.3.8
  characters: ^1.0.0
  fake_async: ^1.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
    - assets/icons/
    - assets/logos/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ec0c6d"
